# Generated by Django 4.2.3 on 2023-08-13 02:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='subscribers',
            field=models.ManyToManyField(related_name='news_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
